#!/bin/bash

# Soundfont files in reversed order
SOUNDFONTS=(
    "/usr/share/sounds/sf2/FluidR3_GS.sf2"
    "/usr/share/sounds/sf2/FluidR3_GM.sf2"
    "/usr/share/sounds/sf2/Timbres Of Heaven GM_GS_XG_SFX V 3.4 Final.sf2"
)

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 INPUT.mid [...]" >&2
    exit 1
fi
for i in "$@"
do
    fluidsynth -r 48000 -O float -F "$(dirname -- "$i")/$(basename -- "$i" .mid).wav" -- "${SOUNDFONTS[@]}" "$i"
done
