#!/bin/bash

# Timidity++ can not handle MIDI files with more than 1048575 events, so we
# will use FluidSynth for those files.
# Parallel rendering is disabled since the kind of files mentioned above often
# have a huge number of notes playing at the same time and parallel rendering
# may often fail. (But it will be much slower.)

# Soundfont files in reversed order
SOUNDFONTS=(
    "/usr/share/sounds/sf2/FluidR3_GS.sf2"
    "/usr/share/sounds/sf2/FluidR3_GM.sf2"
    "/usr/share/sounds/sf2/Timbres Of Heaven GM_GS_XG_SFX V 3.4 Final.sf2"
)

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 INPUT.mid [...]" >&2
    exit 1
fi
for i in "$@"
do
    fluidsynth -r 48000 -O float -o synth.min-note-length=0 -o synth.parallel-render=False -o synth.polyphony=65535 -F "$(dirname -- "$i")/$(basename -- "$i" .mid).wav" -- "${SOUNDFONTS[@]}" "$i"
done
