#!/bin/bash

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 INPUT.mid [...]" >&2
    exit 1
fi
for i in "$@"
do
    timidity --output-stereo -OwS -Aa -a -C0 --reverb=G --preserve-silence --no-polyphony-reduction -o "$(dirname -- "$i")/$(basename -- "$i" .mid).wav" -- "$i"
done
