#!/bin/bash

# Timidity++ can not handle MIDI files with more than 1048575 events, so we
# will use FluidSynth for those files.
# Parallel rendering is disabled since the kind of files mentioned above often
# have a huge number of notes playing at the same time and parallel rendering
# may often fail. (But it will be much slower.)

# Soundfont files in reversed order
SOUNDFONTS=(
    /usr/share/soundfonts/FluidR3_GS.sf2
    /usr/share/soundfonts/FluidR3_GM.sf2
    /usr/share/soundfonts/acoustic_grand_piano_ydp_20080910.sf2
)

[ -z "$1" ] || fluidsynth -i -n -o audio.driver=file -o audio.file.name="$(basename "$1" .mid).wav" -o synth.min-note-length=0 -o synth.parallel-render=False -o synth.polyphony=65535 "${SOUNDFONTS[@]}" "$1"

