#!/bin/sh

[ -z "$1" ] || (timidity --output-stereo -OwS -Aa -a -C0 --reverb=G --preserve-silence --no-polyphony-reduction -o "$(basename "$1" .mid).wav" "$1" && oggenc -q 3 -o "$(basename "$1" .mid).ogg" "$(basename "$1" .mid).wav" && rm "$(basename "$1" .mid).wav")

