#!/bin/bash

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 INPUT.mid [...]" >&2
    exit 1
fi
for i in "$@"
do
    TEMPFILE=$(mktemp --tmpdir tmp.XXXXXXXXXX.wav) &&
    timidity --output-stereo -OwS -Aa -a -C0 --reverb=G --preserve-silence --no-polyphony-reduction -o "$TEMPFILE" -- "$i" &&
    flac -f -8 --replay-gain -o "$(dirname -- "$i")/$(basename -- "$i" .mid).flac" -- "$TEMPFILE"
    rm "$TEMPFILE"
done
