#!/bin/bash

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 protocol://INPUT.mid [...]" >&2
    exit 1
fi
for i in "$@"
do
    curl -o /tmp/midi-$$.mid "$(echo -n "$i" | sed -e 's/midishow\.com\/midi\/\(.*\)\.html/midishow\.com\/midi\/file\/\1\.mid/' -e 's/gangqinpu\.com\/play\.asp\x3fid=\/\?/gangqinpu\.com\//')" &&
    LC_ALL='en_US.UTF-8' timidity -iat -Os --output-stereo -Aa -a -C0 --reverb=G --preserve-silence --no-polyphony-reduction /tmp/midi-$$.mid
    rm /tmp/midi-$$.mid
done
